### ISSUE TITLE
Build a guided tour

### ISSUE THREAD

**Issue by rodolfomartinez** [Oinweb/py-fly#30]
Summary:
It would be helpful to build a short guided tour/motions for the app that is active on first login, and points to certain key elements with an explanation. We can discuss in person.

**Comment by viralrain** [comment]
Guided tour currently being built:
Items completed:
 - Dashboard (goes over entire interface)
 - My Goals
 - Savings Goal
 - Credit Goal
 - Long term goal

Items remaining:
 - Profile (This one will take awhile like the dashboard since there is a lot to explain
 - Notifications
 - Help (I'm thinking this should become a contact form page where users can send us a message if they are having trouble)
 - Learning
 - Course
 - Course Quiz
 - Resources

I'm sure there are some missing from this list, but this is mainly what's in the menu. 
@rodolfomartinez basically how the tour works right now is there is a question mark icon next to the menu icon in the top bar, when clicked it opens a speech bubble type box that has a continue (or if its the last bubble finish) button.  Some of the bubbles perform actions, like on the goals pages, the input boxes and button are highlighted when they are being explained, and like on the dashboard page the menu opens and closes automatically to allow explaining what each nav option brings the user to.
I've attached some screenshots below for you to take a look.
![1](https://cloud.githubusercontent.com/assets/4483034/13544465/41750234-e244-11e5-9482-8b2762cc4815.png)
![2](https://cloud.githubusercontent.com/assets/4483034/13544464/41748a5c-e244-11e5-925d-9b7cbb82952a.png)
![3](https://cloud.githubusercontent.com/assets/4483034/13544463/4174394e-e244-11e5-8038-d87fdcb0ef31.png)
![4](https://cloud.githubusercontent.com/assets/4483034/13544466/41768fd2-e244-11e5-88f7-042add4a2269.png)
![5](https://cloud.githubusercontent.com/assets/4483034/13544468/4178e50c-e244-11e5-8ffe-3438ad34c11b.png)
![6](https://cloud.githubusercontent.com/assets/4483034/13544467/4177c078-e244-11e5-8ac0-e86cb753baae.png)
![7](https://cloud.githubusercontent.com/assets/4483034/13544470/417f8312-e244-11e5-9838-7fe608a6a051.png)
![8](https://cloud.githubusercontent.com/assets/4483034/13544471/41803726-e244-11e5-9183-b07666396541.png)
![9](https://cloud.githubusercontent.com/assets/4483034/13544469/417f1526-e244-11e5-9fb9-4369b6d8f0a4.png)

**Comment by rodolfomartinez** [comment]
Awesome!

**Comment by viralrain** [comment]
Most pages now have a guided tour.  If there's a page that doesn't (like the locked goals pages) then let me know if you think we need a tour for those pages, but I think most things are covered
