### ISSUE TITLE
Course UI

### ISSUE THREAD

**Issue by rodolfomartinez** [Oinweb/py-fly#38]
Summary:
Each course needs a UI page. This will be basic; just a video (2-3 minutes) that plays with a pause/play button, stop, full screen, and back to learning.

**Comment by viralrain** [comment]
Sample course page completed, using videojs -> http://videojs.com/getting-started/#download as the video player, course videos will have to be in mp4 or webm or anything else the standard html5 video player can play.
We can either use this plugin, or have a oinweb youtube channel and just embed the course videos from there, but I'll leave it up to you.
This player is nice because there aren't any ads, and you don't get distracted by being shown a list of similar videos afterwards.

**Comment by rodolfomartinez** [comment]
Ok I like this concept in app, but maybe YouTube could be a way to start monetizing this? Thoughts @bartmika ?

**Comment by viralrain** [comment]
Any more discussion on this? Personally I think the youtube videos would be better because the javascript video player seems to have trouble with going full screen and also with resizing dynamically with the page.

**Comment by viralrain** [comment]
I changed the video to an embedded youtube video which seems to work a bit better as far as resizing and fitting the whole width of the page, as well as resizing properly when resizing the page, and also being able to properly go fullscreen.  So @rodolfomartinez I'll leave it up to you to create a fly app youtube channel where we can store our course videos.
I think this will be a better solution than using html5 video.  Also, we don't have to worry about storing the videos and taking up space, so bonus!

**Comment by bartmika** [comment]
Took @viralrain recommendation and added YouTube Video implementation for the Course Details page. Closing issue.

**Comment by rodolfomartinez** [comment]
Ok create content ticket and assign to me
