### ISSUE TITLE
Landing Page - Contact form

### ISSUE THREAD

**Issue by rodolfomartinez** [Oinweb/py-fly#42]
Summary:
Can we come up with some method of handling contact form submissions - email may be easiest, or could we implement something like Django CMS and have them saved to the database and retreivable via admin?

**Comment by viralrain** [comment]
Hey @bartmika, the relevant code for doing the ajax call is in static/js/landpage/contact_me.js

**Comment by viralrain** [comment]
Oh, and I created a test account for the mailing, the user is oinwebmail@gmail.com, the password is 123password!

**Comment by rodolfomartinez** [comment]
@bartmika we will need to properly solve using gmail for contact stuff - we
need to solve the attempt sign in blocked that we get from comics cantina

On Fri, Mar 4, 2016 at 3:23 PM, Chad Smith <notifications@github.com> wrote:

> Oh, and I created a test account for the mailing, the user is
> oinwebmail@gmail.com, the password is 123password!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Oinweb/py-fly/issues/42#issuecomment-192451737>.
>



-- 
Sincerely,
Rodolfo Martinez
(519)521-3135 / (281)674-5103
Skype: rodolfo-reimar
CEO The Shooting Star Press inc.
www.LuchaComics.com

Be sure to follow @LuchaComics !

**Comment by viralrain** [comment]
I just fixed this problem, the problem was the form elements didn't have any name attributes for some reason.  I also altered the send script a little bit because the form doesn't use ajax, it submits the form then gets a redirect back to the landing page with a response variable that holds info about whether the message was sent or not.
I used the same method with the contact form for py-fly and it seems to work decently enough.
